### ISSUE TITLE
Error: Cannot read property XXX of undefined

### ISSUE THREAD

**Issue by GuilhermeIwane** [catamphetamine/read-excel-file#35]
Hi!

When I try to read a sheet, I get this exception: 

> Cannot read property '0' of undefined 
at readXlsx (<NODE_MODULES_PATH>\node_modules\read-excel-file\commonjs\readXlsx.js:71:35)
at readXlsxFileContents (<NODE_MODULES_PATH>\node_modules\read-excel-file\commonjs\readXlsxFileContents.js:22:38)
at <NODE_MODULES_PATH>\node_modules\read-excel-file\commonjs\readXlsxFileNode.js:33:47
at < anonymous >
at process._tickCallback (internal/process/next_tick.js:189:7)

that's my schema definition:

`EXCEL_SHEET_SCHEMA = {
            'COLUMN_1': {
                prop: 'column_1',
                type: String
            }
}`

In attachments is the content file.

![Excel_sheet](https://user-images.githubusercontent.com/41975892/62821720-c39a7180-bb4f-11e9-8743-fb4a96f105c8.PNG)

Anybody could help me?

**Comment by catamphetamine** [comment]
Provide the file
