### ISSUE TITLE
xls files support

### ISSUE THREAD

**Issue by llermaly** [catamphetamine/read-excel-file#47]
Hello, I'm trying to parse a small xls file , I will attach it here.

Error : 

`Error: invalid signature: 0x7abfbbef
    at /Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/lib/parse.js:62:26
    at tryCatcher (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/LLERMALY/Documents/proyectos/doggis-server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
`

If I save it as xlsx works but I don't want the client to do that, and the file is generated from another system.

Is there a way to work around this? I read about the unzipper lib in xls in another libraries : 
https://github.com/exceljs/exceljs/issues/28

[test.xls.zip](https://github.com/catamphetamine/read-excel-file/files/3776131/test.xls.zip)

Thanks

**Comment by llermaly** [comment]
https://github.com/catamphetamine/read-excel-file/issues/46
