### ISSUE TITLE
Unexpected identifier issue

### ISSUE THREAD

**Issue by danuw** [catamphetamine/read-excel-file#7]
Hi,

I have literally just done the npm install command and create a index.js file with the node sample.

when I do `node index.js` I get the following error:
```
/path-to-myfolder/index.js:1
(function (exports, require, module, __filename, __dirname) { import readXlsxFile from 'read-excel-file/node'
                                                                     ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```
Any ideas please?

Thanks

Dan

btw, I am using 
node v10.8.0
npm 6.4.1

**Comment by catamphetamine** [comment]
You're using ES6.
Node doesn't support ES6.
