### ISSUE TITLE
Error: invalid signature: 0x75646f6d

### ISSUE THREAD

**Issue by mubasharrasheed** [catamphetamine/read-excel-file#81]
Here is the error I'm facing with simple xlsx file:
`Error: invalid signature: 0x75646f6d
    at /home/mb/workspace/reach/node_modules/unzipper/lib/parse.js:62:26
    at tryCatcher (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/mb/workspace/reach/node_modules/unzipper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)`

While it's working for some other files. Can you please look into it?

**Comment by catamphetamine** [comment]
Looks like an error in the `unzipper` package.
You could report it to them then.
